version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=http://localhost:5001
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:5001
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    volumes:
      - backend-db:/app/instance
    ports:
      - "5001:5000"

volumes:
  backend-db:
